// @flow
export const FLASH_ERROR = 'FLASH_ERROR'
export const FLASH_ERRORS_RESET = 'FLASH_ERRORS_RESET'
export const FLASH_INFO = 'FLASH_INFO'

export const SIGN_UP_REQUESTED = 'SIGN_UP_REQUESTED'
export const SIGN_UP_SUCCEEDED = 'SIGN_UP_SUCCEEDED'
export const SIGN_UP_FAILED = 'SIGN_UP_FAILED'

export const LOGIN_REQUESTED = 'LOGIN_REQUESTED'
export const LOGIN_SUCCEEDED = 'LOGIN_SUCCEEDED'
export const LOGIN_FAILED = 'LOGIN_FAILED'
export const RESET_LOGIN_PAGE_STATE = 'RESET_LOGIN_PAGE_STATE'

// Two-Factor Login
export const LOGIN_TWO_FACTOR_VERIFICATION_REQUESTED = 'LOGIN_TWO_FACTOR_VERIFICATION_REQUESTED'
export const LOGIN_TWO_FACTOR_VERIFICATION_SUCCEEDED = 'LOGIN_TWO_FACTOR_VERIFICATION_SUCCEEDED'
export const LOGIN_TWO_FACTOR_VERIFICATION_FAILED = 'LOGIN_TWO_FACTOR_VERIFICATION_FAILED'

export const LOGOUT_REQUESTED = 'LOGOUT_REQUESTED'
export const LOGOUT_SUCCEEDED = 'LOGOUT_SUCCEEDED'
export const LOGOUT_FAILED = 'LOGOUT_FAILED'
export const RESET_USER_STATE = 'RESET_USER_STATE'

export const CONFIRM_EMAIL_ADDRESS_SUCCEEDED = 'CONFIRM_EMAIL_ADDRESS_SUCCEEDED'

export const RESUME_SESSION_REQUESTED = 'RESUME_SESSION_REQUESTED'
export const RESUME_SESSION_SUCCEEDED = 'RESUME_SESSION_SUCCEEDED'
export const RESUME_SESSION_FAILED = 'RESUME_SESSION_FAILED'


export const FORGOT_PASSWORD_EMAIL_REQUESTED = 'FORGOT_PASSWORD_EMAIL_REQUESTED'
export const FORGOT_PASSWORD_EMAIL_SUCCEEDED = 'FORGOT_PASSWORD_EMAIL_SUCCEEDED'
export const FORGOT_PASSWORD_EMAIL_FAILED = 'FORGOT_PASSWORD_EMAIL_FAILED'

export const FORGOT_PASSWORD_RESET_REQUESTED = 'FORGOT_PASSWORD_RESET_REQUESTED'
export const FORGOT_PASSWORD_RESET_SUCCEEDED = 'FORGOT_PASSWORD_RESET_SUCCEEDED'
export const FORGOT_PASSWORD_RESET_FAILED = 'FORGOT_PASSWORD_RESET_FAILED'


// Initial fetches after successful login or resume session.
export const APP_SESSION_FETCHES_REQUESTED = "APP_SESSION_FETCHES_REQUESTED"
export const APP_SESSION_FETCHES_SUCCEEDED = "APP_SESSION_FETCHES_SUCCEEDED"
export const APP_SESSION_FETCHES_FAILED = "APP_SESSION_FETCHES_FAILED"

// Initial #/trade page request (have to verify valid market)
export const TRADE_PAGE_FETCHES_REQUESTED = "TRADE_PAGE_FETCHES_REQUESTED"
export const TRADE_PAGE_FETCHES_SUCCEEDED = "TRADE_PAGE_FETCHES_SUCCEEDED"
export const TRADE_PAGE_FETCHES_FAILED = "TRADE_PAGE_FETCHES_FAILED"

// Initial trade page fetches after marketId verified
export const TRADE_MARKET_FETCHES_REQUESTED = "TRADE_MARKET_FETCHES_REQUESTED"
export const TRADE_MARKET_FETCHES_SUCCEEDED = "TRADE_MARKET_FETCHES_SUCCEEDED"
export const TRADE_MARKET_FETCHES_FAILED = "TRADE_MARKET_FETCHES_FAILED"

// Initial #/wallet page fetches
export const WALLET_PAGE_FETCHES_REQUESTED = "WALLET_PAGE_FETCHES_REQUESTED"
export const WALLET_PAGE_FETCHES_SUCCEEDED = "WALLET_PAGE_FETCHES_SUCCEEDED"
export const WALLET_PAGE_FETCHES_FAILED = "WALLET_PAGE_FETCHES_FAILED"

// Initial #/transactions page fetches
export const TRANSACTIONS_PAGE_FETCHES_REQUESTED = "TRANSACTIONS_PAGE_FETCHES_REQUESTED"
export const TRANSACTIONS_PAGE_FETCHES_SUCCEEDED = "TRANSACTIONS_PAGE_FETCHES_SUCCEEDED"
export const TRANSACTIONS_PAGE_FETCHES_FAILED = "TRANSACTIONS_PAGE_FETCHES_FAILED"


export const FETCH_USER_REQUESTED = 'FETCH_USER_REQUESTED'
export const FETCH_USER_SUCCEEDED = 'FETCH_USER_SUCCEEDED'
export const FETCH_USER_FAILED = 'FETCH_USER_FAILED'

export const FETCH_USER_SECURITY_REQUESTED = 'FETCH_USER_SECURITY_REQUESTED'
export const FETCH_USER_SECURITY_SUCCEEDED = 'FETCH_USER_SECURITY_SUCCEEDED'
export const FETCH_USER_SECURITY_FAILED = 'FETCH_USER_SECURITY_FAILED'

export const FETCH_BALANCES_REQUESTED = 'FETCH_BALANCES_REQUESTED'
export const FETCH_BALANCES_SUCCEEDED = 'FETCH_BALANCES_SUCCEEDED'
export const FETCH_BALANCES_FAILED = 'FETCH_BALANCES_FAILED'

export const FETCH_WALLET_TRANSACTIONS_REQUESTED = 'FETCH_WALLET_TRANSACTIONS_REQUESTED'
export const FETCH_WALLET_TRANSACTIONS_SUCCEEDED = 'FETCH_WALLET_TRANSACTIONS_SUCCEEDED'
export const FETCH_WALLET_TRANSACTIONS_FAILED = 'FETCH_WALLET_TRANSACTIONS_FAILED'

export const FETCH_TRANSACTIONS_REQUESTED = 'FETCH_TRANSACTIONS_REQUESTED'
export const FETCH_TRANSACTIONS_SUCCEEDED = 'FETCH_TRANSACTIONS_SUCCEEDED'
export const FETCH_TRANSACTIONS_FAILED = 'FETCH_TRANSACTIONS_FAILED'

export const FETCH_ASSETS_REQUESTED = 'FETCH_ASSETS_REQUESTED'
export const FETCH_ASSETS_SUCCEEDED = 'FETCH_ASSETS_SUCCEEDED'
export const FETCH_ASSETS_FAILED = 'FETCH_ASSETS_FAILED'

export const FETCH_MARKETS_REQUESTED = 'FETCH_MARKETS_REQUESTED'
export const FETCH_MARKETS_SUCCEEDED = 'FETCH_MARKETS_SUCCEEDED'
export const FETCH_MARKETS_FAILED = 'FETCH_MARKETS_FAILED'

export const FEDERATION_REQUESTED = 'FEDERATION_REQUESTED'
export const FEDERATION_SUCCEEDED = 'FEDERATION_SUCCEEDED'
export const FEDERATION_FAILED = 'FEDERATION_FAILED'

export const FETCH_ADDRESS_REQUESTED = 'FETCH_ADDRESS_REQUESTED'
export const FETCH_ADDRESS_SUCCEEDED = 'FETCH_ADDRESS_SUCCEEDED'
export const FETCH_ADDRESS_FAILED = 'FETCH_ADDRESS_FAILED'

// Show/hide send funds modal
export const SHOW_SEND_FUNDS_MODAL = 'SHOW_SEND_FUNDS_MODAL'
export const HIDE_SEND_FUNDS_MODAL = 'HIDE_SEND_FUNDS_MODAL'
export const SHOW_RECEIVE_FUNDS_MODAL = 'SHOW_RECEIVE_FUNDS_MODAL'
export const HIDE_RECEIVE_FUNDS_MODAL = 'HIDE_RECEIVE_FUNDS_MODAL'

// Show/hide Settings Two-Factor Modal
export const SHOW_SETTINGS_TWO_FACTOR_MODAL = 'SHOW_SETTINGS_TWO_FACTOR_MODAL'
export const HIDE_SETTINGS_TWO_FACTOR_MODAL = 'HIDE_SETTINGS_TWO_FACTOR_MODAL'

// Two-Factor Setup
export const SETUP_TWO_FACTOR_FETCH_REQUESTED = 'SETUP_TWO_FACTOR_FETCH_REQUESTED'
export const SETUP_TWO_FACTOR_FETCH_SUCCEEDED = 'SETUP_TWO_FACTOR_FETCH_SUCCEEDED'
export const SETUP_TWO_FACTOR_FETCH_FAILED = 'SETUP_TWO_FACTOR_FETCH_FAILED'

export const SETUP_TWO_FACTOR_VERIFICATION_REQUESTED = 'SETUP_TWO_FACTOR_VERIFICATION_REQUESTED'
export const SETUP_TWO_FACTOR_VERIFICATION_SUCCEEDED = 'SETUP_TWO_FACTOR_VERIFICATION_SUCCEEDED'
export const SETUP_TWO_FACTOR_VERIFICATION_FAILED = 'SETUP_TWO_FACTOR_VERIFICATION_FAILED'
export const CLEAR_SETUP_TWO_FACTOR_VERIFICATION_STATUS = 'CLEAR_TWO_FACTOR_VERIFICATION_STATUS'

export const DISABLE_TWO_FACTOR_REQUESTED = 'DISABLE_TWO_FACTOR_REQUESTED'
export const DISABLE_TWO_FACTOR_SUCCEEDED = 'DISABLE_TWO_FACTOR_SUCCEEDED'
export const DISABLE_TWO_FACTOR_FAILED = 'DISABLE_TWO_FACTOR_FAILED'

// Change password
export const CHANGE_PASSWORD_REQUESTED = 'CHANGE_PASSWORD_REQUESTED'

// BEING USED SEND_FUNDS is SYNCHRONOUS
export const SEND_FUNDS_REQUESTED = 'SEND_FUNDS_REQUESTED'
export const SEND_FUNDS_SUCCEEDED = 'SEND_FUNDS_SUCCEEDED'
export const SEND_FUNDS_FAILED = 'SEND_FUNDS_FAILED'
export const CLEAR_SEND_FUNDS_ERROR = 'CLEAR_SEND_FUNDS_ERROR'

// NOT BEING USED SEND_FUNDS is currently NOT Asynchronous
// Send Funds, creation-success only (API accepted request) but not yet confirmed
export const SEND_FUNDS_CREATION_REQUESTED = 'SEND_FUNDS_CREATION_REQUESTED'
export const SEND_FUNDS_CREATION_SUCCEEDED = 'SEND_FUNDS_CREATION_SUCCEEDED'
export const SEND_FUNDS_CREATION_FAILED = 'SEND_FUNDS_CREATION_FAILED'
// Initial confirmation (while still on SendModal)
export const SEND_FUNDS_INITIAL_CONFIRMATION_SUCCEEDED = 'SEND_FUNDS_INITIAL_CONFIRMATION_SUCCEEDED'
export const SEND_FUNDS_INITIAL_CONFIRMATION_TIMED_OUT = 'SEND_FUNDS_INITIAL_CONFIRMATION_TIMED_OUT'
// END SEND_FUNDS ASYNC action types


// USER FETCH INTERVAL
export const START_USER_FETCH_INTERVAL = "START_USER_FETCH_INTERVAL"
export const CONFIG_USER_FETCH_INTERVAL = "CONFIG_USER_FETCH_INTERVAL"
export const USER_FETCH_INTERVAL = "USER_FETCH_INTERVAL"  // initiate the actual fetch
export const STOP_USER_FETCH_INTERVAL = "STOP_USER_FETCH_INTERVAL"

// Trade Page
export const MARKET_INFO_REQUESTED = "MARKET_INFO_REQUESTED"
export const MARKET_INFO_SUCCEEDED = "MARKET_INFO_SUCCEEDED"
export const MARKET_INFO_FAILED = "MARKET_INFO_FAILED"

export const MARKET_CHART_REQUESTED = "MARKET_CHART_REQUESTED"
export const MARKET_CHART_SUCCEEDED = "MARKET_CHART_SUCCEEDED"
export const MARKET_CHART_FAILED = "MARKET_CHART_FAILED"
export const MARKET_CHART_POINTS_REQUESTED = "MARKET_CHART_POINTS_REQUESTED"

export const MARKET_HISTORY_REQUESTED = "MARKET_HISTORY_REQUESTED"
export const MARKET_HISTORY_SUCCEEDED = "MARKET_HISTORY_SUCCEEDED"
export const MARKET_HISTORY_FAILED = "MARKET_HISTORY_FAILED"

export const ORDER_HISTORY_REQUESTED = "ORDER_HISTORY_REQUESTED"
export const ORDER_HISTORY_SUCCEEDED = "ORDER_HISTORY_SUCCEEDED"
export const ORDER_HISTORY_FAILED = "ORDER_HISTORY_FAILED"

export const FETCH_EXCHANGE_RATES_REQUESTED = "FETCH_EXCHANGE_RATES_REQUESTED"
export const FETCH_EXCHANGE_RATES_SUCCEEDED = "FETCH_EXCHANGE_RATES_SUCCEEDED"
export const FETCH_EXCHANGE_RATES_FAILED = "FETCH_EXCHANGE_RATES_FAILED"

export const FETCH_OPEN_ORDERS_REQUESTED = "FETCH_OPEN_ORDERS_REQUESTED"
export const FETCH_OPEN_ORDERS_SUCCEEDED = "FETCH_OPEN_ORDERS_SUCCEEDED"
export const FETCH_OPEN_ORDERS_FAILED = "FETCH_OPEN_ORDERS_FAILED"

export const MARKETS_TICKER_REQUESTED = 'MARKETS_TICKER_REQUESTED'
export const MARKETS_TICKER_SUCCEEDED = 'MARKETS_TICKER_SUCCEEDED'
export const MARKETS_TICKER_FAILED = 'MARKETS_TICKER_FAILED'

// Trade Buy/Sell
export const TRADE_BUY_REQUESTED = 'TRADE_BUY_REQUESTED'
export const TRADE_BUY_SUCCEEDED = 'TRADE_BUY_SUCCEEDED'
export const TRADE_BUY_FAILED = 'TRADE_BUY_FAILED'

export const TRADE_SELL_REQUESTED = 'TRADE_SELL_REQUESTED'
export const TRADE_SELL_SUCCEEDED = 'TRADE_SELL_SUCCEEDED'
export const TRADE_SELL_FAILED = 'TRADE_SELL_FAILED'

export const SHOW_TRADE_MODAL = 'SHOW_TRADE_MODAL'
export const HIDE_TRADE_MODAL = 'HIDE_TRADE_MODAL'

export const TRADE_FORM_PRICE_CHANGED = "TRADE_FORM_PRICE_CHANGED"
export const TRADE_FORM_AMOUNT_CHANGED = "TRADE_FORM_AMOUNT_CHANGED"
export const TRADE_FORM_TOTAL_CHANGED = "TRADE_FORM_TOTAL_CHANGED"

export const TRADE_CANCEL_ORDER_REQUESTED = "TRADE_CANCEL_ORDER_REQUESTED"
export const TRADE_CANCEL_ORDER_SUCCEEDED = "TRADE_CANCEL_ORDER_SUCCEEDED"
export const TRADE_CANCEL_ORDER_FAILED = "TRADE_CANCEL_ORDER_FAILED"

export const IMPORT_WALLET_REQUESTED = 'IMPORT_WALLET_REQUESTED'
export const IMPORT_WALLET_SUCCEEDED = 'IMPORT_WALLET_SUCCEEDED'
export const IMPORT_WALLET_FAILED = 'IMPORT_WALLET_FAILED'
